{
  imports = [
    ./modules/amdgpu_top.nix
    ./modules/archives.nix
    ./modules/aria2.nix
    ./modules/bat.nix
    ./modules/btop.nix
    ./modules/duf.nix
    ./modules/eza.nix
    ./modules/fish.nix
    ./modules/fzf.nix
    ./modules/git.nix
    ./modules/hyfetch.nix
    ./modules/hyperfine.nix
    ./modules/imagemagick.nix
    ./modules/imv.nix
    ./modules/jq.nix
    ./modules/less.nix
    ./modules/mat2.nix
    ./modules/mpv.nix
    ./modules/ncdu.nix
    ./modules/neovim
    ./modules/parted.nix
    ./modules/qalculate.nix
    ./modules/ripgrep.nix
    ./modules/tokei.nix
    ./modules/wget.nix
    ./modules/yazi.nix
    ./modules/yt-dlp.nix
    ./modules/zathura.nix
    ./modules/zps.nix
  ];
}
